name: socialbunkr_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.5.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  google_fonts: ^6.2.1 # Added for Poppins font
  intl: ^0.20.0
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0
  razorpay_flutter: ^1.3.6
  open_file: ^3.3.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
